openapi: 3.0.1
info:
  title: Location Intelligence Places
  description: Mastercard DW EDS Location Intelligence Places API
  termsOfService: "https://developer.mastercard.com/terms-of-use"
  contact:
    name: MasterCard Developers
    url: https://developer.mastercard.com/
    email: developers@mastercard.com
  version: 1.0.0
servers:
  - url: https://api.mastercard.com/location-intelligence/places-locator
    description: Production server (uses live data)
  - url: https://sandbox.api.mastercard.com/location-intelligence/places-locator
    description: Sandbox server (testing environment)
tags:
  - name: Merchant Category Codes
    description: Merchant Category Code Controller
  - name: Merchant Industry Codes
    description: Merchant Industry Code Controller
  - name: Places
    description: Place Controller
paths:
  /merchant-category-codes:
    get:
      tags:
        - Merchant Category Codes
      summary: Get all active merchant category codes
      description: 'Returns a list of Merchant Category Codes ordered by Merchant Category Code or Merchant Category Name, depending on user input. The list will be ordered by Merchant Category Name by default.'
      operationId: getAllMerchantCategoryCodesUsingGet
      parameters:
        - name: limit
          in: query
          description: Maximum number of items to return.
          required: false
          schema:
            type: integer
            default: 25
            format: int32
            example: 25
        - name: offset
          in: query
          description: Number of items to skip before returning the results.
          required: false
          schema:
            type: integer
            default: 0
            format: int32
            example: 0
        - name: sort
          in: query
          description: Sort order for the metrics. Use -field for sort by field descending and +field for sorting by field ascending. Multiple field are separated by ','.
          required: false
          schema:
            type: string
            default: +merchantCategoryName
            example: +merchantCategoryName
      responses:
        200:
          description: Successfully retrieved merchant category codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedMerchantCategoryCode'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
      deprecated: false
  /merchant-category-codes/mcc-codes/{mcc_code}:
    get:
      tags:
        - Merchant Category Codes
      summary: Get merchant category code by code
      description: Get merchant category code by code
      operationId: getByMccCodeUsingGET
      parameters:
        - name: mcc_code
          in: path
          description: mcc_code
          required: true
          schema:
            type: string
          example: '0004'
      responses:
        200:
          description: This code represents the category that a merchant location may be under and is supported by most payment providers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantCategoryCode'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
      deprecated: false
  /merchant-industry-codes:
    get:
      tags:
        - Merchant Industry Codes
      summary: Get all active merchant industry codes
      description: Returns a list of Merchant Industries ordered by Merchant Industry Codes or Merchant Industry Name depending on user input. The list will be ordered by Merchant Industry Name by default.
      operationId: getAllIndustryCodesUsingGET
      parameters:
        - name: limit
          in: query
          description: Maximum number of items to return.
          required: false
          schema:
            type: integer
            default: 25
            format: int32
            example: 25
        - name: offset
          in: query
          description: Number of items to skip before returning the results.
          required: false
          schema:
            type: integer
            default: 0
            format: int32
            example: 0
        - name: sort
          in: query
          description:  Sort order for the metrics. Use -field for sort by field descending and +field for sorting by field ascending. Multiple field are separated by ','.
          required: false
          schema:
            type: string
            default: +industryName
            example: +industryName
      responses:
        200:
          description: Successfully retrieved merchant industry codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedMerchantIndustryCode'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
      deprecated: false
  /merchant-industry-codes/industries/{industry}:
    get:
      tags:
        - Merchant Industry Codes
      summary: Get merchant industry code details by industry code
      description: Returns Merchant Industry code details by  Industry code
      operationId: getByIndustryUsingGET
      parameters:
        - name: industry
          in: path
          description: industry
          required: true
          example: ACC
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved merchant industry code details by industry
            code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantIndustryCode'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
      deprecated: false
  /places/searches:
    post:
      tags:
        - Places
      summary: 'Search for places '
      description: 'Returns detailed information on merchants based on the provided, query parameter'
      operationId: searchPlacesUsingPOST
      parameters:
        - name: limit
          in: query
          description: Maximum number of items to return.
          required: false
          schema:
            type: integer
            default: 25
            format: int32
            example: 25
        - name: offset
          in: query
          description: Number of items to skip before returning the results.
          required: false
          schema:
            type: integer
            default: 0
            format: int32
            example: 0
      requestBody:
        description: placeSearchRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceSearchRequest'
        required: true
      responses:
        200:
          description: Successfully retrieved search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPlaceInfo'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
      deprecated: false
  /places/{location_id}:
    get:
      tags:
        - Places
      summary: 'Get the location details by using location id'
      description: 'Returns detailed information on merchants based on the provided, query parameter, locationId'
      operationId: getPlaceByLocationIdUsingGET
      parameters:
        - name: location_id
          in: path
          description: location_id
          required: true
          example: 300945305
          schema:
            type: integer
            format: int64

      responses:
        200:
          description: Successfully retrieved detailed information on merchants based
            on the provided path parameter, locationId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceInfo'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
      deprecated: false
components:
  responses:
    BadRequestError:
      description: Something was wrong with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: location-intelligence-places
                  ReasonCode: INVALID_REQUEST
                  Description: "Method argument type is invalid"
                  Recoverable: true
                  Details: null
              - Error:
                  Source: location-intelligence-places
                  ReasonCode: INVALID_REQUEST_PARAMETER
                  Description: "Offset index must not be less than zero"
                  Recoverable: true
                  Details: null
              - Error:
                  Source: location-intelligence-places
                  ReasonCode: INVALID_REQUEST_PARAMETER
                  Description: "Limit must not be less than one"
                  Recoverable: true
                  Details: null
    UnauthorizedError:
      description: Authentication information was missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: Gateway
                  ReasonCode: UNAUTHORIZED
                  Description: "Project doesn't have access to the requested service"
                  Recoverable: false
                  Details: "Full authentication is required to access this resource"
    ForbiddenError:
      description: Insufficient permissions for interacting with the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: Gateway
                  ReasonCode: PERMISSION_DENIED
                  Description: "You don't seem authorized to do that"
                  Recoverable: false
    NotFoundError:
      description: URI didn't match an existing resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: location-intelligence-places
                  ReasonCode: ENTITY_NOT_FOUND
                  Description: "You requested something we don't have"
                  Recoverable: false
                  Details: null
  schemas:
    ErrorResponse:
      description: Only returned in the event of an error condition
      type: object
      required:
        - Errors
      properties:
        Errors:
          type: object
          required:
            - Error
          properties:
            Error:
              $ref: '#/components/schemas/Errors'
    Errors:
      type: array
      minItems: 1
      description: Only returned in the event of an error condition
      items:
        $ref: '#/components/schemas/Error'
    Error:
      type: object
      description: >-
        Details of the error condition such as the source of the error, reason code for the error,
        if the error is recoverable, and details about the error
      required:
        - Source
        - ReasonCode
        - Description
        - Recoverable
      properties:
        Source:
          description: The application that generated this error
          type: string
          minLength: 0
          maxLength: 150
          example: location-intelligence-places
        ReasonCode:
          description: A unique constant identifying the error case encountered during transaction processing
          type: string
          minLength: 0
          maxLength: 150
          example: INVALID_REQUEST
        Description:
          description: Short description of the ReasonCode field
          type: string
          minLength: 0
          maxLength: 150
          example: Data value or format is invalid
        Recoverable:
          description: Indicates whether this error will always be returned for this request, or retrying could change the outcome
          type: boolean
          example: true
        Details:
          description: Description of the issue
          type: string
          minLength: 0
          maxLength: 150
    PageResponse:
      title: PageResponse
      type: object
      properties:
        total:
          type: integer
          format: int32
          example: 25
        limit:
          type: integer
          format: int32
          example: 0
        offset:
          type: integer
          format: int32
          example: 0
    PagedMerchantCategoryCode:
      allOf:
        - $ref: '#/components/schemas/PageResponse'
        - type: object
          description: Paged response of Merchant Category Codes
          required:
            - items
          properties:
            items:
              type: array
              description: Array of Merchant Category Codes
              items:
                $ref: '#/components/schemas/MerchantCategoryCode'
    PagedMerchantIndustryCode:
      allOf:
        - $ref: '#/components/schemas/PageResponse'
        - type: object
          description: Paged response of Merchant Industry Codes
          required:
            - items
          properties:
            items:
              type: array
              description: Array of Merchant Industry Codes
              items:
                $ref: '#/components/schemas/MerchantIndustryCode'
    PagedPlaceInfo:
      allOf:
        - $ref: '#/components/schemas/PageResponse'
        - type: object
          description: Paged response of Merchant Industry Codes
          required:
            - items
          properties:
            items:
              type: array
              description: Array of Places
              items:
                $ref: '#/components/schemas/PlaceInfo'
    MerchantCategoryCode:
      title: MerchantCategoryCode
      type: object
      properties:
        merchantCategoryCode:
          type: string
          example: '0004'
          description: This code represents the category that a merchant location
            may be under and is supported by most payment providers
        merchantCategoryName:
          type: string
          example: AIR CARRIERS  AIRLINES-NOT ELSEWHERE CLASSIFIED
          description: This is the name of the Merchant Category that accompanies
            the MCC Code which identifies the category a merchant falls under
      description: Merchant Category Code
    MerchantIndustryCode:
      title: MerchantIndustryCode
      type: object
      properties:
        industry:
          type: string
          example: ACC
          description: This code represents the industry that a merchant location
            may be under and is supported by most payments providers
        industryName:
          type: string
          example: Accommodations
          description: This is the name of the Industry that accompanies the Industry
            Code which identifies the industry a merchant falls under
      description: Merchant Industry Code
    PlaceSearchRequest:
      title: PlaceSearchRequest
      type: object
      properties:
        distance:
          type: integer
          description: Distance measurement for calculating the radius search.
            The length of distance from the centroid point. Value integer(<15).
          format: int64
          example: 10
        place:
          $ref: '#/components/schemas/PlaceFilter'
        radiusSearch:
          type: boolean
          description: Switches on the radius search algorithm to be performed with
            places from a given centroid. Value boolean (true) switches on the radius
            search algorithm. NOTE - Distance, Latitude and Longitude are REQUIRED for radius
            search algorithm
          example: true
        unit:
          type: string
          description: Unit of measurement for calculating the radius search. Optional.
            Measurement of distance unit in miles or kilometers. Value string (m or
            km
          enum:
            - MILE
            - KM
      description: Place Search Request
    PlaceFilter:
      title: PlaceFilter
      required:
        - countryCode
      type: object
      properties:
        aggregateMerchantId:
          type: integer
          description: Filter results by the aggregate merchant ID
          format: int64
        aggregateMerchantName:
          type: string
          description: Filter results by the aggregate merchant name
        cityName:
          type: string
          example: 'O FALLON'
          description: The city for the desired location
        countryCode:
          type: string
          example: 'US'
          description: The country code for the desired location
        dateEstablished:
          type: string
          description: The date of establishment for the desired location
          format: date
        dmaCode:
          type: string
          description: Filter results by the DMA code
        dunAndBradstreetNumber:
          type: string
          description: The Dun and Bradstreet number for the desired location
        geocodeQualityIndicator:
          type: string
          description: Utilize to only return businesses with the certain characteristics like a rooftop
        hasCashBack:
          type: boolean
          description: Utilize to only return locations that have cash back
        hasNfc:
          type: boolean
          example: true
          description: Utilize to only return locations that support nfc
        hasPayAtThePump:
          type: boolean
          description: Utilize to only return locations that have pay at the pump
        industry:
          type: string
          description: The industry for the desired location
        isInBusiness180Day:
          type: boolean
          description: Utilize to only return businesses that have had business the last 180 days
        isInBusiness30Day:
          type: boolean
          description: Utilize to only return businesses that have had business the last 30 days
        isInBusiness360Day:
          type: boolean
          description: Utilize to only return businesses that have had business the last 360 days
        isInBusiness60Day:
          type: boolean
          description: Utilize to only return businesses that have had business the last 60 days
        isInBusiness7Day:
          type: boolean
          description: Utilize to only return businesses that have had business the last 7 days
        isInBusiness90Day:
          type: boolean
          description: Utilize to only return businesses that have had business the last 90 days
        isNewBusiness:
          type: boolean
          example: false
          description: Utilize to only return new or recently opened businesses
        keyAggregateMerchantId:
          type: integer
          format: int64
          description: Filter results by the key aggregate merchant ID
        latitude:
          type: string
          example: 38.7467
          description: Utilize to only return businesses at the selected latitude
        legalCorporateName:
          type: string
          description: The legal corporate name for the desired location
        locationId:
          type: integer
          format: int64
          description: Filter results by the Location ID
        longitude:
          type: string
          example: -90.7464
          description: Utilize to only return businesses at the selected longitude
        mccCode:
          type: string
          description: Filter results by the Merchant Category Code
        merchantName:
          type: string
          description: The merchant name for the desired location
        msaCode:
          type: string
          description: Filter results by the MSA code
        naicsCode:
          type: string
          description: Filter results by the NAICS code
        parentAggregateMerchantId:
          type: string
          description: Filter results by the parent aggregate merchant ID
        parentAggregateMerchantName:
          type: string
          description: Filter results by the parent aggregate merchant name
        postalCode:
          type: string
          description: The postal code for the desired location
        primaryChannelOfDistribution:
          type: string
          description: 'Utilize to only return businesses that utilize Brick and Mortar or Web as their primary channel. O = Online / Ecommerce, B = Brick & Mortar, N = Non-Store Retail'
          example: 'B'
        stateProvinceCode:
          type: string
          example: 'MO'
          description: The state for the desired location
        streetAddress:
          type: string
          description: The street address for the desired location
        superIndustry:
          type: string
          description: The super industry for the desired location
        telephoneNumber:
          type: string
          description: The telephone number for the desired location
      description: Place Filter
    PlaceInfo:
      title: PlaceInfo
      required:
        - countryCode
        - locationId
      type: object
      properties:
        aggregateMerchantId:
          type: integer
          format: int64
          example: 12077
          description: Merchant Aggregate ID groups merchant locations by chain. This is the first level of aggregation
        aggregateMerchantName:
          type: string
          example: 'FAMOUS FOOTWEAR'
          description: The aggregate merchant name of this merchant location
        cityName:
          type: string
          example: 'O FALLON'
          description: The city for the desired location
        cleansedCityName:
          type: string
          example: 'O FALLON'
          description: The cleansed city name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
        cleansedCountryCode:
          type: string
          example: 'US'
          description: The cleansed country code is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
        cleansedLegalCorporateName:
          type: string
          example: 'BROWN SHOE COMPANY INC'
          description: The cleansed legal corporate name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
        cleansedMerchantName:
          type: string
          example: 'FAMOUS FOOTWEAR #1749'
          description: The cleansed merchant name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
        cleansedPostalCode:
          type: string
          example: '63368-7929'
          description: The cleansed postal code is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
        cleansedStateProvinceCode:
          type: string
          example: MO
          description: The cleansed state is provided by Mastercard matching its transaction data with another Data Partner
        cleansedStreetAddress:
          type: string
          example: '2254 HIGHWAY K'
          description: The cleansed street address is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
        cleansedTelephoneNumber:
          type: string
          example: '6362814068'
          description: The cleansed telephone number is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
        countryCode:
          type: string
          example: US
          description: The country code for the desired location
        dateEstablished:
          type: string
          format: date
          example: '1999-10-23'
          description: The date of establishment for the desired location
        dmaCode:
          type: string
          example: '609'
          description: A Designated Market Area or a DMA is a geographic  area that  represents specific television markets as defined by and updated annually by the Nielsen Company. (US Only)
        geocodeQualityIndicator:
          type: string
          example: STOREFRONT
          description: 'Geocoding quality indicating the specificity of the geo location such as Storefront, Rooftop, Street, Postcode, Admin, Other or None'
        hasCashBack:
          type: boolean
          example: false
          description: Indicates if the merchants provides cash back
        hasNfc:
          type: boolean
          example: true
          description: Indicates if the merchant supports near field communications (nfc)
        hasPayAtThePump:
          type: boolean
          example: false
          description: Indicates if a merchant has pay at the pump
        industry:
          type: string
          example: SHS
          description: The industry for the desired location
        isInBusiness180Day:
          type: boolean
          example: true
          description: Indicates if this location was in business in the last 180 days
        isInBusiness30Day:
          type: boolean
          example: true
          description: Indicates if this location was in business in the last 30 days
        isInBusiness360Day:
          type: boolean
          example: true
          description: Indicates if this location was in business in the last in the last 360 days
        isInBusiness60Day:
          type: boolean
          example: true
          description: Indicates if this location was in business in the last 60 days
        isInBusiness7Day:
          type: boolean
          example: true
          description: Indicates if this location was in business in the last 7 days
        isInBusiness90Day:
          type: boolean
          example: true
          description: Indicates if this location was in business in the last 90 days
        isNewBusiness:
          type: boolean
          example: false
          description: Indicates if new or recently opened businesses
        keyAggregateMerchantId:
          type: integer
          format: int64
          example: 12077
          description: The Mastercard defined key aggregate merchant id joins together different channels of one merchant under the same id
        latitude:
          type: number
          format: double
          example: 38.778083
          description: The latitude geo coordinate position of this merchant location up to 6 decimal precision digits
        legalCorporateName:
          type: string
          example: BROWN SHOE COMPANY INC
          description: The legal corporate name for the desired location
        locationId:
          type: integer
          format: int64
          example: 300945305
          description: The Mastercard assigned location id representing this merchant location
        longitude:
          type: number
          format: double
          example: -90.699706
          description: The longitude geo coordinate position of this merchant location up to 6 decimal precision digits
        mccCode:
          type: string
          example: '5661'
          description: The Merchant Category Code for the desired location
        merchantName:
          type: string
          example: 'FAMOUSFOOTWEAR#1749'
          description: The merchant name for the desired location
        msaCode:
          type: string
          example: '7040'
          description: The metropolitan statistical area (US only). These codes group merchants into metropolitan area
        naicsCode:
          type: string
          example: '448210'
          description: North American Industry Classification System Code
        parentAggregateMerchantId:
          type: string
          example: '10002109'
          description: The ID code for the parent aggregate merchant of this merchant location. This helps to further aggregate merchants under one identifier
        parentAggregateMerchantName:
          type: string
          example: 'CALERES INC'
          description: The name for the parent aggregate merchant of this merchant location. This helps to further aggregate merchants under one identifier
        postalCode:
          type: string
          example: '63368'
          description: The postal code for the desired location
        primaryChannelOfDistribution:
          type: string
          example: B
          description: 'Return businesses that utilize Brick and Mortar or Web as their primary channel. \r\nO = Online - Ecommerce, B = Brick and Mortar, N = Non-Store Retail'
        stateProvinceCode:
          type: string
          example: MO
          description: The state for the desired location
        streetAddress:
          type: string
          example: '2254 HWY K'
          description: The street address for the desired location
        superIndustry:
          type: string
          example: 'AAP'
          description: The super industry for the desired location
        telephoneNumber:
          type: string
          description: The telephone number for the desired location
      description: Place Info

